### ISSUE TITLE
Parallel investigators missing

### ISSUE THREAD

**Issue by profwacko** [Kamalisk/arkhamdb-json-data#937] opened 2021-04-09 02:42 UTC
I don't seem to see the ff:
Parallel Daisy Walker: https://arkhamdb.com/card/90001 
Skids: https://arkhamdb.com/card/90008
or
Agnes: https://arkhamdb.com/card/90017

Is this a missing card issue or is it not handled by ArkhamDB yet?

**Comment by drawntotheflame** [comment] 2021-04-09 07:49
Cards that are a duplicate of another (as the parallel cards are) are marked as 'hidden' so that the DB doesn't think there are two separate investigators with the same name. You can still access them by building a deck for any of them and switching to parallel front or back.

**Comment by profwacko** [comment] 2021-04-10 09:42
I see, I'm also checking the API, the cards are implemented but it seems there are no image info for the cards implemented as well?

https://arkhamdb.com/api/public/card/90017

**Comment by fspoettel** [comment] 2024-12-12 22:40
@zzorba IMO we can close this one, it's an arkhamdb issue if anything

**Closed** 2024-12-12 23:59 UTC
